<?php

namespace App\Form;

use App\Entity\Document;
use App\Entity\Person;
use App\Entity\Procedure;
use App\Entity\Request;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class DocumentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Document Name',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Enter document name'
                ]
            ])
            ->add('type', ChoiceType::class, [
                'label' => 'Document Type',
                'choices' => [
                    'Input Document (Required from citizen)' => 'input',
                    'Output Document (Generated by system)' => 'output'
                ],
                'attr' => [
                    'class' => 'form-select'
                ],
                'placeholder' => 'Select document type'
            ])
            ->add('request', EntityType::class, [
                'class' => Request::class,
                'choice_label' => function(Request $request) {
                    return sprintf('%s - %s (%s)', 
                        $request->getReference(), 
                        $request->getPerson()->getFullName(),
                        $request->getProcedure()->getPname()
                    );
                },
                'label' => 'Associated Request',
                'placeholder' => 'Select a request (optional)',
                'required' => false,
                'attr' => [
                    'class' => 'form-select request-select',
                    'data-search' => 'true',
                    'onchange' => 'updateRequestRelatedFields(this.value)'
                ],
                'query_builder' => function ($repository) {
                    return $repository->createQueryBuilder('r')
                        ->leftJoin('r.person', 'p')
                        ->leftJoin('r.procedure', 'proc')
                        ->addSelect('p', 'proc')
                        ->where('r.isDeleted = :deleted')
                        ->setParameter('deleted', false)
                        ->orderBy('r.submittedAt', 'DESC');
                }
            ])
            ->add('procedure', EntityType::class, [
                'class' => Procedure::class,
                'choice_label' => 'pname',
                'label' => 'Related Procedure',
                'placeholder' => 'Select a procedure (optional)',
                'required' => false,
                'attr' => [
                    'class' => 'form-select'
                ],
                'query_builder' => function ($repository) {
                    return $repository->createQueryBuilder('p')
                        ->where('p.isActive = :active')
                        ->setParameter('active', true)
                        ->orderBy('p.pname', 'ASC');
                }
            ])
            ->add('person', EntityType::class, [
                'class' => Person::class,
                'choice_label' => function(Person $person) {
                    return sprintf('%s (%s)', $person->getFullName(), $person->getNationalId());
                },
                'label' => 'Associated Citizen',
                'placeholder' => 'Select a citizen (optional)',
                'required' => false,
                'attr' => [
                    'class' => 'form-select person-select',
                    'data-live-search' => 'true'
                ],
                'query_builder' => function ($repository) {
                    return $repository->createQueryBuilder('p')
                        ->where('p.isDeleted = :deleted')
                        ->setParameter('deleted', false)
                        ->orderBy('p.lastName', 'ASC')
                        ->addOrderBy('p.firstName', 'ASC');
                }
            ])
            ->add('status', ChoiceType::class, [
                'label' => 'Document Status',
                'choices' => [
                    'Draft' => 'draft',
                    'Pending Review' => 'pending',
                    'Approved' => 'approved',
                    'Rejected' => 'rejected',
                    'Expired' => 'expired',
                    'Active' => 'active'
                ],
                'attr' => [
                    'class' => 'form-select'
                ],
                'data' => $options['data']->getStatus() ?: 'draft'
            ])
            ->add('expirationDate', DateType::class, [
                'label' => 'Expiration Date',
                'required' => false,
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control',
                    'min' => (new \DateTime())->format('Y-m-d')
                ],
                'help' => 'Leave empty if the document does not expire'
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description',
                'required' => false,
                'attr' => [
                    'class' => 'form-control',
                    'rows' => 4,
                    'placeholder' => 'Enter document description'
                ]
            ])
            ->add('documentTemplates', ChoiceType::class, [
                'label' => 'Document Templates',
                'mapped' => false,
                'required' => false,
                'choices' => $this->getDocumentTemplates(),
                'attr' => [
                    'class' => 'form-select',
                    'onchange' => 'updateDocumentPreview(this.value, this.options[this.selectedIndex].text)'
                ],
                'placeholder' => 'Select a document template'
            ])
            ->add('documentFile', FileType::class, [
                'label' => 'Upload Document File',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '10M',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/msword',
                            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                            'application/vnd.ms-excel',
                            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                            'image/jpeg',
                            'image/png'
                        ],
                        'mimeTypesMessage' => 'Please upload a valid document file',
                    ])
                ],
                'attr' => [
                    'class' => 'form-control',
                    'accept' => '.pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png',
                    'onchange' => 'previewDocument(this)'
                ]
            ])
            ->add('removeDocument', CheckboxType::class, [
                'label' => 'Remove current document',
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'class' => 'form-check-input'
                ]
            ])
            ->add('isRequired', CheckboxType::class, [
                'label' => 'Required Document',
                'required' => false,
                'attr' => [
                    'class' => 'form-check-input'
                ],
                'help' => 'Check if this document is mandatory for the procedure'
            ])
            ->add('displayOrder', IntegerType::class, [
                'label' => 'Display Order',
                'attr' => [
                    'class' => 'form-control',
                    'min' => 0
                ],
                'data' => $options['data']->getDisplayOrder() ?: 0
            ])
            ->add('isActive', CheckboxType::class, [
                'label' => 'Active',
                'required' => false,
                'attr' => [
                    'class' => 'form-check-input'
                ],
                'data' => $options['data']->isActive() !== false
            ]);

        // Add event listener to handle request selection
        $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
            $data = $event->getData();
            if (isset($data['request']) && !empty($data['request'])) {
                // If a request is selected, we might want to auto-populate related fields
                // This will be handled in the controller or via JavaScript
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Document::class,
        ]);
    }

    private function getDocumentTemplates(): array
    {
        return [
            'Identity Documents' => [
                'Birth Certificate Template' => 'birth-certificate-template.pdf',
                'National ID Template' => 'national-id-template.pdf',
                'Passport Template' => 'passport-template.pdf',
                'Nationality Certificate Template' => 'nationality-certificate-template.pdf'
            ],
            'Civil Status Documents' => [
                'Marriage Certificate Template' => 'marriage-certificate-template.pdf',
                'Death Certificate Template' => 'death-certificate-template.pdf',
                'Divorce Certificate Template' => 'divorce-certificate-template.pdf'
            ],
            'Business Documents' => [
                'Business License Template' => 'business-license-template.pdf',
                'Tax Certificate Template' => 'tax-certificate-template.pdf',
                'Commercial Registration Template' => 'commercial-registration-template.pdf',
                'Import License Template' => 'import-license-template.pdf',
                'Export License Template' => 'export-license-template.pdf'
            ],
            'Educational Documents' => [
                'Diploma Certificate Template' => 'diploma-certificate-template.pdf',
                'Transcript Template' => 'transcript-template.pdf',
                'Equivalence Certificate Template' => 'equivalence-certificate-template.pdf',
                'Translation Certificate Template' => 'translation-certificate-template.pdf'
            ],
            'Legal Documents' => [
                'Criminal Background Check Template' => 'criminal-background-template.pdf',
                'Legal Certificate Template' => 'legal-certificate-template.pdf',
                'Court Document Template' => 'court-document-template.pdf',
                'Loss Declaration Template' => 'loss-declaration-template.pdf'
            ],
            'Medical Documents' => [
                'Medical Certificate Template' => 'medical-certificate-template.pdf',
                'Health Permit Template' => 'health-permit-template.pdf',
                'Vaccination Record Template' => 'vaccination-record-template.pdf'
            ],
            'Transport Documents' => [
                'Driving License Template' => 'driving-license-template.pdf',
                'Vehicle Registration Template' => 'vehicle-registration-template.pdf',
                'Transport License Template' => 'transport-license-template.pdf'
            ],
            'Property Documents' => [
                'Land Title Template' => 'land-title-template.pdf',
                'Building Permit Template' => 'building-permit-template.pdf',
                'Property Certificate Template' => 'property-certificate-template.pdf'
            ]
        ];
    }
}