<?php

namespace App\Form;

use App\Entity\Document;
use App\Entity\Procedure;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class DocumentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Document Name',
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Enter document name'
                ]
            ])
            ->add('type', ChoiceType::class, [
                'label' => 'Document Type',
                'choices' => [
                    'Input Document (Required from citizen)' => 'input',
                    'Output Document (Generated by system)' => 'output'
                ],
                'attr' => [
                    'class' => 'form-select'
                ],
                'placeholder' => 'Select document type'
            ])
            ->add('procedure', EntityType::class, [
                'class' => Procedure::class,
                'choice_label' => 'pname',
                'label' => 'Related Procedure',
                'placeholder' => 'Select a procedure (optional)',
                'required' => false,
                'attr' => [
                    'class' => 'form-select'
                ],
                'query_builder' => function ($repository) {
                    return $repository->createQueryBuilder('p')
                        ->where('p.isActive = :active')
                        ->setParameter('active', true)
                        ->orderBy('p.pname', 'ASC');
                }
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description',
                'required' => false,
                'attr' => [
                    'class' => 'form-control',
                    'rows' => 4,
                    'placeholder' => 'Enter document description'
                ]
            ])
            ->add('documentTemplates', ChoiceType::class, [
                'label' => 'Document Templates',
                'mapped' => false,
                'required' => false,
                'choices' => $this->getDocumentTemplates(),
                'attr' => [
                    'class' => 'form-select',
                    'onchange' => 'updateDocumentPreview(this.value, this.options[this.selectedIndex].text)'
                ],
                'placeholder' => 'Select a document template'
            ])
            ->add('documentFile', FileType::class, [
                'label' => 'Upload Document File',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '10M',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/msword',
                            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                            'application/vnd.ms-excel',
                            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                            'image/jpeg',
                            'image/png'
                        ],
                        'mimeTypesMessage' => 'Please upload a valid document file',
                    ])
                ],
                'attr' => [
                    'class' => 'form-control',
                    'accept' => '.pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png'
                ]
            ])
            ->add('removeDocument', CheckboxType::class, [
                'label' => 'Remove current document',
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'class' => 'form-check-input'
                ]
            ])
            ->add('isRequired', CheckboxType::class, [
                'label' => 'Required Document',
                'required' => false,
                'attr' => [
                    'class' => 'form-check-input'
                ]
            ])
            ->add('displayOrder', IntegerType::class, [
                'label' => 'Display Order',
                'attr' => [
                    'class' => 'form-control',
                    'min' => 0
                ],
                'data' => $options['data']->getDisplayOrder() ?: 0
            ])
            ->add('isActive', CheckboxType::class, [
                'label' => 'Active',
                'required' => false,
                'attr' => [
                    'class' => 'form-check-input'
                ],
                'data' => $options['data']->isActive() !== false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Document::class,
        ]);
    }

    private function getDocumentTemplates(): array
    {
        return [
            'Identity Documents' => [
                'Birth Certificate Template' => 'birth-certificate-template.pdf',
                'National ID Template' => 'national-id-template.pdf',
                'Passport Template' => 'passport-template.pdf',
            ],
            'Civil Status Documents' => [
                'Marriage Certificate Template' => 'marriage-certificate-template.pdf',
                'Death Certificate Template' => 'death-certificate-template.pdf',
                'Divorce Certificate Template' => 'divorce-certificate-template.pdf',
            ],
            'Business Documents' => [
                'Business License Template' => 'business-license-template.pdf',
                'Tax Certificate Template' => 'tax-certificate-template.pdf',
                'Commercial Registration Template' => 'commercial-registration-template.pdf',
            ],
            'Educational Documents' => [
                'Diploma Certificate Template' => 'diploma-certificate-template.pdf',
                'Transcript Template' => 'transcript-template.pdf',
                'Equivalence Certificate Template' => 'equivalence-certificate-template.pdf',
            ],
            'Legal Documents' => [
                'Criminal Background Check Template' => 'criminal-background-template.pdf',
                'Legal Certificate Template' => 'legal-certificate-template.pdf',
                'Court Document Template' => 'court-document-template.pdf',
            ],
            'Medical Documents' => [
                'Medical Certificate Template' => 'medical-certificate-template.pdf',
                'Health Permit Template' => 'health-permit-template.pdf',
                'Vaccination Record Template' => 'vaccination-record-template.pdf',
            ]
        ];
    }
}